### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MomboteQ** [Matoking/nanolib#15]
I have error:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    balance=10000000000000000000000000
  File "/usr/local/lib/python3.7/dist-packages/nanolib/blocks.py", line 245, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python3.7/dist-packages/nanolib/blocks.py", line 83, in wrapper
    setter(self, new)
  File "/usr/local/lib/python3.7/dist-packages/nanolib/blocks.py", line 103, in wrapper
    setter(self, val)
  File "/usr/local/lib/python3.7/dist-packages/nanolib/blocks.py", line 116, in wrapper
    setter(self, val)
  File "/usr/local/lib/python3.7/dist-packages/nanolib/blocks.py", line 739, in set_previous
    validate_public_key(previous)
  File "/usr/local/lib/python3.7/dist-packages/nanolib/accounts.py", line 85, in validate_public_key
    if len(public_key) != 64 or not is_hex(public_key):
TypeError: object of type 'property' has no len()
```

**Comment by zontyp** [comment]
Hello @MomboteQ 

could you please share code of test.py to debug the error please.

Thanks and best regards,
karan ahuja
